
### Add one participations

POST http://localhost:3000/participations/
Content-Type: application/json

{
  "id_quizz": 3,
  "id_user": 1,
  "score": 450
}
### Get Best Scores

GET http://localhost:3000/participations/bestScores/3


###

GET http://localhost:3000/participations/personnalsBestScores?id_quizz=3&id_user=1