### View question by id
GET http://localhost:3000/questions/37

### View all questions. Or the questions of a specific quizz
GET http://localhost:3000/questions?quizz=1

### Add a question
POST http://localhost:3000/questions/
Content-Type: application/json

{
    "id_quizz": 2,
    "question": "J'aime les pommes?"
}

### Delete a question
DELETE http://localhost:3000/questions?quizz=1&question=36

### Update question
PUT http://localhost:3000/questions/37
Content-Type: application/json

{
    "question": "J omsddjiqjdes?"
}