
### Create user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name":"Tchoupi",
  "email": "tchoupi@gmail.com",
  "password":"123"
}

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "stefanIPL@gmail.com",
  "password":"123"
}


### follow user

POST http://localhost:3000/users/subscribe
Content-Type: application/json

{
  "id_user": 1,
  "id_follower": 2
}

### get users by filter on email or name
GET http://localhost:3000/users/filter/ipl


### user is admin ? true or false
GET http://localhost:3000/users


### user is admin ? true or false
GET http://localhost:3000/users/a



### user is admin ? true or false
GET http://localhost:3000/users/isAdmin/1

### get number of subscribers for user 19
GET http://localhost:3000/users/subscribers/19

### get number of subscriptions for user 20
GET http://localhost:3000/users/subscriptions/20

### user is banned ? true or false
GET http://localhost:3000/users/isBanned/1

### Update ban by id
PUT http://localhost:3000/users/ban
Content-Type: application/json

{
  "id_user":10
}

### Update ban by email
PUT http://localhost:3000/users/ban/email
Content-Type: application/json

{
  "email":"damas@gmail.com"
}

### Update admin
PUT http://localhost:3000/users/upAdmin
Content-Type: application/json

{
  "id_user":10
}

### Update admin by email
PUT http://localhost:3000/users/upAdmin/email
Content-Type: application/json

{
  "email":"damas@gmail.com"
}